// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

require('dotenv').config();

const fs = require('fs');

// Docs versioning.
//
// The list of released versions (for the version dropdown and /versions page)
// comes from the COMMITTED manifest (versioning/manifest.json) — always present,
// even in the fast Vercel build that renders no snapshots.
//
// The version SNAPSHOTS themselves (versioned_docs/, versioned_sidebars/,
// versions.json) are NOT committed. They are regenerated from git history by CI
// only for the archive build (see .github/workflows/build-docs-archive.yml) and
// served as a static archive. The Vercel build therefore has no snapshots on
// disk and renders only the current docs (fast — it gates merges).
let docsManifest = {versions: []};
let manifestVersions = []; // newest-first version strings
try {
  docsManifest = JSON.parse(
    fs.readFileSync(__dirname + '/versioning/manifest.json', 'utf8'),
  );
  manifestVersions = (docsManifest.versions || []).map((v) => v.version).reverse();
} catch (e) {
  manifestVersions = [];
}
const hasManifest = manifestVersions.length > 0;

// Are the frozen snapshots present on disk (i.e. regenerated by CI)? versions.json
// is written by generate_versions.sh alongside versioned_docs/.
let builtVersions = [];
try {
  builtVersions = JSON.parse(fs.readFileSync(__dirname + '/versions.json', 'utf8'));
} catch (e) {
  builtVersions = [];
}
const snapshotsPresent = Array.isArray(builtVersions) && builtVersions.length > 0;

// DOCS_VERSIONS_BUILD_LIMIT (only meaningful when snapshots are present):
//   current  (default) -> current docs only (fast; Vercel)
//   all                -> every version (CI archive build)
//   20                 -> current + the latest 20 released versions
const versionsBuildLimitRaw = (
  process.env.DOCS_VERSIONS_BUILD_LIMIT || 'current'
).toLowerCase();
const buildAllVersions = versionsBuildLimitRaw === 'all';
const currentOnly = ['current', 'none', '0', ''].includes(versionsBuildLimitRaw);
let includedReleasedVersions = [];
if (snapshotsPresent && !currentOnly) {
  const n = buildAllVersions
    ? builtVersions.length
    : Math.max(1, parseInt(versionsBuildLimitRaw, 10) || 0);
  includedReleasedVersions = builtVersions.slice(0, n);
}
// Whether THIS build actually renders released version snapshots.
const buildsVersions =
  snapshotsPresent && (buildAllVersions || includedReleasedVersions.length > 0);

// Base URL of the CI-built version archive (e.g.
// https://berriai.github.io/litellm-docs, a custom domain, or "" for a
// same-origin Vercel rewrite). The navbar dropdown and /versions page link
// frozen versions here when this build doesn't render them itself.
const docsArchiveUrl = (process.env.DOCS_ARCHIVE_URL || '').replace(/\/$/, '');

// In the current-only (Vercel) build, "main"/current lives at /docs/; in a
// multi-version build it lives at /docs/main/ and the latest release is at /docs/.
const currentDocsPath = buildsVersions ? '/docs/main/' : '/docs/';
// URL for a released version: same-origin if rendered in this build, else archive.
const releasedVersionUrl = (version) => {
  const builtHere =
    buildsVersions &&
    (buildAllVersions || includedReleasedVersions.includes(version));
  if (builtHere) return `/docs/${version}/`;
  return `${docsArchiveUrl}/docs/${version}/`;
};

// @ts-ignore
const lightCodeTheme = require('prism-react-renderer/themes/vsLight');
// @ts-ignore
const darkCodeTheme = require('prism-react-renderer/themes/nightOwl');

const inkeepApiKey = process.env.INKEEP_API_KEY;
// Conditional check: docs should work if this key is missing.
const hasInkeepSearch = Boolean(inkeepApiKey);

const inkeepConfig = {
  baseSettings: {
    apiKey: inkeepApiKey,
    organizationDisplayName: 'liteLLM',
    primaryBrandColor: '#4965f5',
    theme: {
      styles: [
        {
          key: "custom-theme",
          type: "style",
          value: `
            .ikp-chat-button__button {
              margin-right: 80px !important;
            }
          `,
        },
      ],
      syntaxHighlighter: {
        lightTheme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    },
  },
  searchSettings: {
    searchBarPlaceholder: 'Search docs, guides, API reference...',
    debounceTimeMs: 0,
    maxResults: 7 
  },
  aiChatSettings: {
    aiAssistantName: 'LiteLLM AI',
    chatSubjectName: 'LiteLLM',
    aiAssistantAvatar: '/img/favicon.ico',
    placeholder: 'Ask anything about LiteLLM...',
    introMessage: 'Hi! I can help you with LiteLLM — proxy setup, model routing, caching, spend tracking, and more. What would you like to know?',
    exampleQuestions: [
      'How do I set up the LiteLLM proxy?',
      'How do I route requests across multiple models?',
      'How do I enable response caching?',
      'How do I track spend per team or API key?',
    ],
    exampleQuestionsLabel: 'Common questions',
    isFirstExampleQuestionHighlighted: true,
    shouldOpenLinksInNewTab: true,
    isCopyChatButtonVisible: true,
    isShareButtonVisible: false,
    prompts: [
      'You are a helpful assistant specializing in LiteLLM. Answer questions about setup, configuration, model routing, the proxy server, caching, logging, and spend tracking. When referencing configuration options, include YAML or Python code examples where helpful. If a question is outside the scope of LiteLLM, politely redirect the user to the relevant docs or GitHub.',
    ],
  },
};

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'liteLLM',
  tagline: 'Simplify LLM API Calls',
  favicon: '/img/favicon.ico', 

  // Set the production url of your site here. Overridable so the CI archive can
  // build for a different host (e.g. GitHub Pages) without code changes.
  url: process.env.DOCS_SITE_URL || 'https://docs.litellm.ai/',
  // Set the /<baseUrl>/ pathname under which your site is served.
  // For GitHub Pages project sites this is often '/<repo>/'.
  baseUrl: process.env.DOCS_BASE_URL || '/',

  // The version archive is a supplementary mirror of the canonical site; keep it
  // out of search engines so it doesn't compete with docs.litellm.ai.
  noIndex: Boolean(process.env.DOCS_ARCHIVE_BUILD),

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  // Exposed to client pages (e.g. /versions) to build version links that point
  // at the static archive for versions not rendered in the current build.
  customFields: {
    docsArchiveUrl,
    buildAllVersions,
    builtReleasedVersions: includedReleasedVersions,
    currentDocsPath,
  },

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  plugins: [
    require('./plugins/optimize-images'),
    // Adds <meta name="robots" content="noindex"> + a canonical link to the
    // latest equivalent page on every non-latest docs version (old pip versions
    // and the in-development "main"). Prevents duplicate-content SEO dilution
    // across ~73 versions and keeps crawlers / Inkeep scoped to the latest docs.
    ...(buildsVersions
      ? [[require('./plugins/versioned-seo'), {}]]
      : []),
    ...(hasInkeepSearch
      ? [
          [
            '@inkeep/cxkit-docusaurus',
            {
              SearchBar: {
                ...inkeepConfig,
              },
              ChatButton: {
                ...inkeepConfig,
              },
            },
          ],
        ]
      : []),
    [
      '@docusaurus/plugin-ideal-image',
      {
        quality: 75,
        max: 1280,
        min: 640,
        steps: 2,
        disableInDev: false,
      },
    ],
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'release-notes',
        path: './release_notes',
        routeBasePath: 'release_notes',
        sidebarPath: require.resolve('./sidebars-release-notes.js'),
        async sidebarItemsGenerator({defaultSidebarItemsGenerator, docs, ...args}) {
          const items = await defaultSidebarItemsGenerator({docs, ...args});

          // Build map of doc id -> year from frontmatter date
          const docYearMap = {};
          for (const doc of docs) {
            const date = doc.frontMatter && doc.frontMatter.date;
            if (date) {
              const year = new Date(date).getFullYear();
              docYearMap[doc.id] = year;
            }
          }

          function parseVersion(str) {
            const match = (str || '').match(/v?(\d+)\.(\d+)\.(\d+)/);
            if (!match) return [0, 0, 0];
            return [parseInt(match[1]), parseInt(match[2]), parseInt(match[3])];
          }
          function compareVersionsDesc(a, b) {
            const [aMaj, aMin, aPatch] = parseVersion(a.label || a.id || '');
            const [bMaj, bMin, bPatch] = parseVersion(b.label || b.id || '');
            if (bMaj !== aMaj) return bMaj - aMaj;
            if (bMin !== aMin) return bMin - aMin;
            return bPatch - aPatch;
          }

          // Flatten and transform doc items (filter index, shorten labels)
          function flattenDocs(list) {
            const result = [];
            for (const item of list) {
              if (item.type === 'doc' && item.id === 'index') continue;
              if (item.type === 'doc') {
                const label = item.id.replace(/\/index$/, '');
                result.push({...item, label});
              } else if (item.type === 'category') {
                if (item.link && item.link.type === 'doc' && item.link.id !== 'index') {
                  const id = item.link.id;
                  const label = id.replace(/\/index$/, '');
                  result.push({type: 'doc', id, label});
                } else {
                  result.push(...flattenDocs(item.items));
                }
              }
            }
            return result;
          }

          const docItems = flattenDocs(items);

          // Group by year
          const byYear = {};
          for (const item of docItems) {
            const year = docYearMap[item.id] || 'Other';
            if (!byYear[year]) byYear[year] = [];
            byYear[year].push(item);
          }

          // Sort each year's items by version descending
          for (const year of Object.keys(byYear)) {
            byYear[year].sort(compareVersionsDesc);
          }

          // Build categories sorted by year descending
          const years = Object.keys(byYear).sort((a, b) => {
            // Object.keys() returns strings; avoid numeric subtraction type errors.
            const na = Number.parseInt(a, 10);
            const nb = Number.parseInt(b, 10);
            return nb - na;
          });
          return years.map(year => ({
            type: 'category',
            label: String(year),
            collapsed: year !== String(years[0]),
            items: byYear[year],
          }));
        },
      },
    ],
    [
      '@docusaurus/plugin-content-blog',
      {
        id: 'blog',
        path: './blog',
        routeBasePath: 'blog',
        blogTitle: 'Blog',
        blogSidebarTitle: 'All Posts',
        blogSidebarCount: 'ALL',
        postsPerPage: 'ALL',
        showReadingTime: false,
        sortPosts: 'descending',
        include: ['**/index.{md,mdx}'],
        remarkPlugins: [require('./src/remark/raw-markdown')],
      },
    ],

    () => ({
      name: 'cripchat',
      injectHtmlTags() {
        return {
          headTags: [
            {
              tagName: 'script',
              innerHTML: `window.$crisp=[];window.CRISP_WEBSITE_ID="be07a4d6-dba0-4df7-961d-9302c86b7ebc";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();`,
            },
          ],
        };
      },
    }),
    // Ensure gtag exists before the GA script loads.
    () => ({
      name: 'gtag-shim',
      injectHtmlTags() {
        return {
          headTags: [
            {
              tagName: 'script',
              innerHTML: `window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}if(!window.gtag){window.gtag=gtag;}`,
            },
          ],
        };
      },
    }),
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        gtag:
          process.env.NODE_ENV === 'production'
            ? {
                trackingID: 'G-K7K215ZVNC',
                anonymizeIP: true,
              }
            : undefined,
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          remarkPlugins: [require('./src/remark/raw-markdown')],
          // When versions have been backfilled, serve the newest pip release at
          // /docs/ (the default) and expose the unversioned working tree as the
          // in-development "main" at /docs/main/ with an "unreleased" banner.
          // Older versions automatically get the "unmaintained" banner.
          ...(buildsVersions
            ? {
                // Multi-version build (CI archive): newest release served at
                // /docs/, current working tree as "main" at /docs/main/.
                lastVersion: builtVersions[0],
                versions: {
                  current: {label: 'main 🚧', path: 'main', banner: 'unreleased'},
                },
                ...(buildAllVersions
                  ? {}
                  : {onlyIncludeVersions: ['current', ...includedReleasedVersions]}),
              }
            : snapshotsPresent
            ? {
                // Snapshots on disk but building current-only: render just the
                // working-tree docs at /docs/, ignoring the frozen snapshots.
                lastVersion: 'current',
                onlyIncludeVersions: ['current'],
              }
            : {}),
        },
        blog: false, // Disable the default blog plugin from preset-classic
        pages: {},
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  future: {
    experimental_faster: {
      swcJsLoader: true,
      swcJsMinimizer: true,
      swcHtmlMinimizer: true,
      lightningCssMinimizer: true,
      mdxCrossCompilerCache: true,
      // Use the Rust-based rspack bundler instead of webpack. Essential for
      // many-version builds: rspack uses a fraction of webpack's memory, which
      // otherwise OOMs (>8GB heap) when bundling dozens of doc versions.
      rspackBundler: true,
    },
  },

  themes: ['@docusaurus/theme-mermaid'],
  markdown: {
    mermaid: true,
  },

  scripts: [
    {
      async: true,
      src: 'https://www.feedbackrocket.io/sdk/v1.2.js',
      'data-fr-id': 'GQwepB0f0L-x_ZH63kR_V',
      'data-fr-theme': 'dynamic',
    }
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: 'img/docusaurus-social-card.png',
      navbar: {
        title: '🚅 LiteLLM',
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'tutorialSidebar',
            position: 'left',
            label: 'Docs',
          },
          {
            type: 'docSidebar',
            sidebarId: 'learnSidebar',
            position: 'left',
            label: 'Learn',
          },
          {
            type: 'docSidebar',
            sidebarId: 'integrationsSidebar',
            position: 'left',
            label: 'Integrations',
          },
          {
            position: 'left',
            label: 'Enterprise',
            to: "docs/enterprise"
          },
          { to: '/release_notes', label: 'Changelog', position: 'left' },
          { to: '/blog', label: 'Blog', position: 'left' },
          // Custom version dropdown built from the manifest (not Docusaurus'
          // docsVersionDropdown), so it lists every release even in the fast
          // current-only build, linking frozen versions to the static archive.
          // `href` is used (not `to`) so links to versions not rendered in THIS
          // build aren't flagged as broken.
          ...(hasManifest
            ? [
                {
                  type: 'dropdown',
                  label: 'Versions',
                  position: 'right',
                  items: [
                    {label: 'main 🚧 (unreleased)', href: currentDocsPath},
                    ...manifestVersions
                      .slice(0, 6)
                      .map((v, i) => ({
                        label: i === 0 ? `${v} (latest)` : v,
                        href: releasedVersionUrl(v),
                      })),
                    {to: '/versions', label: 'All versions →'},
                  ],
                },
              ]
            : []),
          {
            href: 'https://docs.litellm-agent-platform.ai/',
            label: 'LiteLLM Agent Platform',
            position: 'left',
          },
          {
            href: 'https://github.com/BerriAI/litellm',
            position: 'right',
            className: 'header-github-link',
            'aria-label': 'GitHub repository',
          },
          {
            href: 'https://www.litellm.ai/support',
            position: 'right',
            className: 'header-discord-link',
            'aria-label': 'Discord / Slack community',
          },
          ...(hasInkeepSearch
            ? [{type: 'search', position: 'right'}]
            : []),
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              {
                label: 'Getting Started',
                to: 'https://docs.litellm.ai/docs/',
              },
            ],
          },
          {
            title: 'Community',
            items: [
              {
                label: 'Discord',
                href: 'https://discord.com/invite/wuPM9dRgDw',
              },
              {
                label: 'Twitter',
                href: 'https://twitter.com/LiteLLM',
              },
            ],
          },
          {
            title: 'More',
            items: [
              {
                label: 'GitHub',
                href: 'https://github.com/BerriAI/litellm/',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} liteLLM`,
      },
      colorMode: {
        defaultMode: 'light',
        disableSwitch: false,
        respectPrefersColorScheme: true,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
